language: php

php: 5.4

services: mongodb

before_script:
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - php composer.phar --dev install

script: _cli/bin/rbhp test core
